name: Accessibility Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual triggers
  workflow_dispatch:

jobs:
  accessibility:
    name: Accessibility Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install pa11y
        run: npm install -g pa11y-ci
        
      - name: Run Pa11y accessibility tests
        run: |
          # Start a simple HTTP server to serve the site
          npx serve -l 8000 &
          SERVER_PID=$!
          
          # Give the server a moment to start
          sleep 2
          
          # Run accessibility tests
          pa11y-ci --sitemap http://localhost:8000/sitemap.xml || pa11y-ci http://localhost:8000
          
          # Kill the server
          kill $SERVER_PID