name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual triggers
  workflow_dispatch:

jobs:
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install -g htmlhint stylelint stylelint-config-standard eslint

      - name: Check HTML
        run: htmlhint '**/*.html'

      - name: Check CSS
        run: stylelint '**/*.css'

      - name: Check JavaScript
        run: eslint '**/*.js'